Vagrant.configure("2") do |config|
  servers = [
    {
      :hostname => "Node1",
      :box => "bento/ubuntu-18.04",
      :ip => "172.16.1.50",
      :ssh_port => 2200
    },
    {
      :hostname => "Node2",
      :box => "bento/ubuntu-18.04",
      :ip => "172.16.1.51",
      :ssh_port => 2201
    }
  ]

  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]

      node.vm.network "private_network", ip: machine[:ip]
      node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"

      node.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update -y
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository universe -y
        sudo apt-get update -y
        sudo apt-get install -y docker.io
        sudo systemctl enable docker
        sudo systemctl start docker
        sudo usermod -aG docker vagrant
      SHELL

      node.vm.synced_folder "/Users/gianmarco.dauria/Desktop/Ping_Pong/data", "/home/vagrant/data"

      node.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", 1024]
        vb.customize ["modifyvm", :id, "--cpus", 2]
      end

      if machine[:hostname] == "Node1"
        node.vm.provision "file", source: "./portscanner.sh", destination: "/home/vagrant/portscanner.sh"
        node.vm.provision "shell", inline: <<-SHELL
          chmod +x /home/vagrant/portscanner.sh
          chown vagrant:vagrant /home/vagrant/portscanner.sh
        SHELL
      end

    end
  end
end

