# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/9"
  config.vm.hostname = "rocky9"

  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "4096"
    v.vmx["numvcpus"] = "2"
  end

  # Installazione di Ansible nella VM
  config.vm.provision "shell", inline: <<-SHELL
    sudo dnf install -y epel-release
    sudo dnf install -y ansible
  SHELL

  # Esecuzione del playbook Ansible locale
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "/vagrant/playbook.yml"
  end
end

